### ISSUE TITLE
release: automatically generate release announce in blog

### ISSUE THREAD

**Issue by komainu8** [groonga/groonga.org#83]
### What is your problem?

Currently, when releasing a new version, we have to manually create a blog post to announce it. This process is redundant and time-consuming because we already have detailed release notes that cover the changes in the new version.

## Proposed Solution:

Implement a Rake task that automatically generates a blog post.
This will streamline the release process and reduce the manual effort required during releases.

**Comment by komainu8** [comment]
**Image how we want to call this rake task**

```console
$ rake release:blog:announce:generate (...arguments)
```

**TODO**

- [ ] Implement a rake task to generate blog without contents
  - [ ] Implement only interface of the rake tesk #84
  - [ ] Implement the logic of the rake task
- [ ] Write the blog content
- [ ] Implements CI

**Comment by abetomo** [comment]
Already completed?

**Comment by komainu8** [comment]
Yes. This issue has already completed.
So, I close this.
